<?php

declare(strict_types=1);

namespace Andre\AiPageBuilder\Seeders;

use Andre\AiPageBuilder\Ai\SystemPromptBuilder;
use Illuminate\Support\Facades\Schema as DbSchema;

/**
 * Seeds the bundled `app_builder` integration into the AI OpenRouter Gateway —
 * the engine system prompt (architecture + component catalog + output contract,
 * code-generated by SystemPromptBuilder) plus an {{app_context}} placeholder for
 * the per-request live app state. The owner's business guidelines + the user's
 * brief are sent as the conversation body at invoke time.
 *
 * SELF-HEALING: run() uses firstOrCreate on every boot, so deleting the
 * integration just regenerates it next boot — it can't stay gone and break the
 * AI feature. It never clobbers an admin-tuned prompt version (only seeds one on
 * first create). The gateway is OPTIONAL, so its classes are string literals.
 */
class AppBuilderIntegrationSeeder
{
    public const MODEL = 'Andre\\AiGateway\\Models\\AiIntegration';

    public const SERVICE = 'Andre\\AiGateway\\Services\\AiIntegrationService';

    public static function gatewayInstalled(): bool
    {
        return class_exists(self::MODEL) && class_exists(self::SERVICE);
    }

    /**
     * @return bool true when a new integration was created this call
     */
    public function run(): bool
    {
        if (! self::gatewayInstalled()) {
            return false;
        }

        /** @var class-string $model */
        $model = self::MODEL;

        $probe = new $model;
        if (! DbSchema::connection($probe->getConnectionName())->hasTable($probe->getTable())) {
            return false;
        }

        $slug = (string) config('ai-page-builder.ai.app_builder_slug', 'app_builder');

        $integration = $model::firstOrCreate(
            ['slug' => $slug],
            [
                'name' => 'Synapse App Builder',
                'description' => 'AI app generation — emits a validated Build Plan (collections, states, functions, flows, pages) the builder applies. Bundled; do not delete (it self-heals on boot).',
                'provider' => 'openrouter',
                'visibility' => 'internal',
                'is_active' => true,
            ],
        );

        if (! $integration->wasRecentlyCreated) {
            return false;
        }

        app(self::SERVICE)->saveVersion(
            $integration,
            [
                'system_prompt' => self::systemPrompt(),
                'system_prompt_cacheable' => true,
                'models' => [(string) config('ai-page-builder.ai.default_model', 'anthropic/claude-sonnet-4')],
                'default_params' => ['temperature' => 0.2, 'max_tokens' => 8000],
                'prompt_args' => [
                    ['name' => 'app_context', 'type' => 'string', 'required' => false, 'description' => "This app's current collections, states, pages and available components."],
                ],
                'notes' => 'v1: seeded by andrecorugda/ai-page-builder (app builder).',
            ],
            true,
            null,
        );

        return true;
    }

    private static function systemPrompt(): string
    {
        $engine = app(SystemPromptBuilder::class)->build();

        return $engine."\n\n## Current app context\nThe app you are building into currently contains:\n\n{{app_context}}\n\nUse this context to avoid duplicating what already exists and to reference existing items when the user refines.";
    }
}
