<?php

declare(strict_types=1);

namespace Andre\AiPageBuilder\Blocks;

/**
 * The single source of truth for the landing-page section vocabulary.
 *
 * Every section wraps its content in `<section data-pb-block="{key}">` with
 * stable inner class names (pb-{key}__*). GrapesJS registers a component type
 * keyed on the data-pb-block attribute, so any markup using this convention —
 * whether dragged from the block manager or generated by AI — imports as a
 * labelled, editable component instead of an opaque blob.
 */
final class BlockVocabulary
{
    /**
     * @return array<int,SectionBlock>
     */
    public static function all(): array
    {
        return [
            new SectionBlock(
                key: 'hero',
                label: 'Hero',
                category: 'Sections',
                description: 'Headline, subheadline and a primary call-to-action.',
                template: <<<'HTML'
                <section data-pb-block="hero" class="pb-hero" style="padding:5rem 1.5rem;text-align:center;">
                  <h1 class="pb-hero__title" style="font-size:2.75rem;margin:0 0 1rem;">Your headline here</h1>
                  <p class="pb-hero__subtitle" style="font-size:1.25rem;color:#475569;max-width:40rem;margin:0 auto 2rem;">A short, punchy subheadline that explains the value.</p>
                  <a class="pb-hero__cta" href="#" style="display:inline-block;padding:0.85rem 1.75rem;border-radius:0.5rem;background:#4f46e5;color:#fff;text-decoration:none;font-weight:600;">Get started</a>
                </section>
                HTML,
            ),
            new SectionBlock(
                key: 'features',
                label: 'Features',
                category: 'Sections',
                description: 'A grid of feature cards (icon/title/description).',
                template: <<<'HTML'
                <section data-pb-block="features" class="pb-features" style="padding:4rem 1.5rem;">
                  <h2 class="pb-features__title" style="text-align:center;font-size:2rem;margin:0 0 2.5rem;">Features</h2>
                  <div class="pb-features__grid" style="display:grid;grid-template-columns:repeat(3,1fr);gap:1.5rem;max-width:64rem;margin:0 auto;">
                    <div class="pb-features__item" style="padding:1.5rem;border:1px solid #e2e8f0;border-radius:0.75rem;">
                      <h3 style="margin:0 0 0.5rem;">Feature one</h3>
                      <p style="color:#475569;margin:0;">Describe the benefit to the customer.</p>
                    </div>
                    <div class="pb-features__item" style="padding:1.5rem;border:1px solid #e2e8f0;border-radius:0.75rem;">
                      <h3 style="margin:0 0 0.5rem;">Feature two</h3>
                      <p style="color:#475569;margin:0;">Describe the benefit to the customer.</p>
                    </div>
                    <div class="pb-features__item" style="padding:1.5rem;border:1px solid #e2e8f0;border-radius:0.75rem;">
                      <h3 style="margin:0 0 0.5rem;">Feature three</h3>
                      <p style="color:#475569;margin:0;">Describe the benefit to the customer.</p>
                    </div>
                  </div>
                </section>
                HTML,
            ),
            new SectionBlock(
                key: 'pricing',
                label: 'Pricing',
                category: 'Sections',
                description: 'Pricing tiers with plan name, price and a CTA.',
                template: <<<'HTML'
                <section data-pb-block="pricing" class="pb-pricing" style="padding:4rem 1.5rem;">
                  <h2 class="pb-pricing__title" style="text-align:center;font-size:2rem;margin:0 0 2.5rem;">Pricing</h2>
                  <div class="pb-pricing__grid" style="display:grid;grid-template-columns:repeat(3,1fr);gap:1.5rem;max-width:60rem;margin:0 auto;">
                    <div class="pb-pricing__plan" style="padding:2rem;border:1px solid #e2e8f0;border-radius:0.75rem;text-align:center;">
                      <h3 style="margin:0 0 0.5rem;">Starter</h3>
                      <p style="font-size:2rem;font-weight:700;margin:0 0 1rem;">$9<span style="font-size:1rem;color:#64748b;">/mo</span></p>
                      <a href="#" style="display:inline-block;padding:0.6rem 1.25rem;border-radius:0.5rem;background:#4f46e5;color:#fff;text-decoration:none;">Choose</a>
                    </div>
                    <div class="pb-pricing__plan" style="padding:2rem;border:2px solid #4f46e5;border-radius:0.75rem;text-align:center;">
                      <h3 style="margin:0 0 0.5rem;">Pro</h3>
                      <p style="font-size:2rem;font-weight:700;margin:0 0 1rem;">$29<span style="font-size:1rem;color:#64748b;">/mo</span></p>
                      <a href="#" style="display:inline-block;padding:0.6rem 1.25rem;border-radius:0.5rem;background:#4f46e5;color:#fff;text-decoration:none;">Choose</a>
                    </div>
                    <div class="pb-pricing__plan" style="padding:2rem;border:1px solid #e2e8f0;border-radius:0.75rem;text-align:center;">
                      <h3 style="margin:0 0 0.5rem;">Business</h3>
                      <p style="font-size:2rem;font-weight:700;margin:0 0 1rem;">$99<span style="font-size:1rem;color:#64748b;">/mo</span></p>
                      <a href="#" style="display:inline-block;padding:0.6rem 1.25rem;border-radius:0.5rem;background:#4f46e5;color:#fff;text-decoration:none;">Choose</a>
                    </div>
                  </div>
                </section>
                HTML,
            ),
            new SectionBlock(
                key: 'testimonial',
                label: 'Testimonial',
                category: 'Sections',
                description: 'A customer quote with attribution.',
                template: <<<'HTML'
                <section data-pb-block="testimonial" class="pb-testimonial" style="padding:4rem 1.5rem;background:#f8fafc;text-align:center;">
                  <blockquote class="pb-testimonial__quote" style="font-size:1.5rem;max-width:48rem;margin:0 auto 1rem;font-style:italic;">“This product changed how our team works.”</blockquote>
                  <p class="pb-testimonial__author" style="color:#475569;margin:0;font-weight:600;">Jane Doe, CEO at Acme</p>
                </section>
                HTML,
            ),
            new SectionBlock(
                key: 'cta',
                label: 'Call to action',
                category: 'Sections',
                description: 'A closing call-to-action banner.',
                template: <<<'HTML'
                <section data-pb-block="cta" class="pb-cta" style="padding:4rem 1.5rem;text-align:center;background:#4f46e5;color:#fff;">
                  <h2 class="pb-cta__title" style="font-size:2rem;margin:0 0 1rem;">Ready to get started?</h2>
                  <a class="pb-cta__button" href="#" style="display:inline-block;padding:0.85rem 1.75rem;border-radius:0.5rem;background:#fff;color:#4f46e5;text-decoration:none;font-weight:600;">Sign up free</a>
                </section>
                HTML,
            ),
            new SectionBlock(
                key: 'footer',
                label: 'Footer',
                category: 'Sections',
                description: 'A simple footer with links and copyright.',
                template: <<<'HTML'
                <section data-pb-block="footer" class="pb-footer" style="padding:2.5rem 1.5rem;background:#0f172a;color:#cbd5e1;text-align:center;">
                  <p class="pb-footer__links" style="margin:0 0 0.75rem;">
                    <a href="#" style="color:#cbd5e1;text-decoration:none;margin:0 0.75rem;">About</a>
                    <a href="#" style="color:#cbd5e1;text-decoration:none;margin:0 0.75rem;">Pricing</a>
                    <a href="#" style="color:#cbd5e1;text-decoration:none;margin:0 0.75rem;">Contact</a>
                  </p>
                  <p class="pb-footer__copy" style="margin:0;font-size:0.875rem;color:#64748b;">© Your Company. All rights reserved.</p>
                </section>
                HTML,
            ),
        ];
    }

    /**
     * @return array<int,string>
     */
    public static function keys(): array
    {
        return array_map(static fn (SectionBlock $b): string => $b->key, self::all());
    }

    public static function find(string $key): ?SectionBlock
    {
        foreach (self::all() as $block) {
            if ($block->key === $key) {
                return $block;
            }
        }

        return null;
    }

    /**
     * Serializable form for the GrapesJS block manager (JS side).
     *
     * @return array<int,array{key:string,label:string,category:string,template:string,description:string}>
     */
    public static function toArray(): array
    {
        return array_map(static fn (SectionBlock $b): array => $b->toArray(), self::all());
    }
}
